// ibm-training/react/redux-products/src/components/productDetails.tsx
import { FC, useCallback, useEffect, useState } from "react"
import { useNavigate, useParams } from "react-router-dom"
import IProduct from "../model/product"
import httpClient from "../apiClient/httpClient"

export const ProductDetails: FC<any> = () => {

    const { id } = useParams<string>()// react hook that will help us to read path parameter... it will give the id

    const [product, setProduct] = useState<IProduct>({} as IProduct) //{} initializing with an empty oject

    const getProductById = useCallback(async () => {
        const response = await httpClient.getById('http://localhost:3000/products', Number(id))
        setProduct(response)

    }, [])

    useEffect(() => {
        getProductById()
    }, [])

    const navigator = useNavigate()

    return (
        <div className="card-body">
            <div className="row">
                <div className="col-md-3">ProductName</div>
                <div className="col-md-6">{product.productName}</div>
            </div>
            <div className="row">
                <div className="col-md-3">Price</div>
                <div className="col-md-6">{product.price}</div>
            </div>
            <div className="row">
                <div className="col-md-3">ProductAvailability</div>
                <div className="col-md-6">{product.productAvailable}</div>
            </div>
            <div className="row">
                <div className="col-md-3">Rating</div>
                <div className="col-md-6">{product.starRating}</div>
            </div>

            <div className="row">
                <div className="col-md-3">
                    <button className="btn btn-info btn-block" onClick={() => navigator('/products')}>Back</button>
                </div>
                <div className="col-md-6">
                    <button className="btn btn-info btn-block" onClick={() => navigator(`/products/${product.productId}/edit`)}>{`Edit ${product.productName}`}</button>
                </div>
            </div>

        </div>
    )
}

// ibm-training/angular/products-spa-forms/src/app/product-details/product-details.component.ts
import { Component, OnInit } from '@angular/core';
import IProduct from '../model/product';
import { ProductClientService } from '../product-client.service';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-product-details',
  templateUrl: './product-details.component.html',
  styleUrl: './product-details.component.css'
})
export class ProductDetailsComponent implements OnInit {

  product: IProduct | undefined
  errorMessage: string = '';
  constructor(private clientService: ProductClientService,
    private route: ActivatedRoute, private router: Router) {
  }
  //in react we have used useEffect()--- eager calling
  //ngOnIt --lazy calling
  ngOnInit(): void {

    const param = this.route.snapshot.paramMap.get('id')
    if (param) {
      this.clientService.getProductById(+param).subscribe({
        next: product => this.product = product,
        error: err => this.errorMessage = err
      })
    }
  }
  onBack(): void {
    this.router.navigate(['/products'])
  }
}

@if (product) {
<div class="card-body">
  <div class="row">
    <div class="col-md-3">ProductName</div>
    <div class="col-md-6">{{ product.productName }}</div>
  </div>
  <div class="row">
    <div class="col-md-3">Price</div>
    <div class="col-md-6">{{ product.price }}</div>
  </div>
  <div class="row">
    <div class="col-md-3">ProductAvailable</div>
    <div class="col-md-6">{{ product.productAvailable }}</div>
  </div>
  <div class="row">
    <div class="col-md-3">Rating</div>
    <div class="col-md-6">{{ product.starRating }}</div>
  </div>

  <div class="row">
    <div class="col-2">
      <button type="button" class="btn btn-info btn-block" (click)="onBack()">
        Back
      </button>
    </div>
    <div class="col-2">
      <button
        type="button"
        class="btn btn-info btn-block"
        [routerLink]="['/products', product.productId, 'edit']"
      >
        {{ product.productName }}
      </button>
    </div>
  </div>
</div>
}
