// ibm-training/angular/products-app/src/app/products-list/products-list.component.ts
import { Component } from '@angular/core';
import products from '../data/products'
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-products-list',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './products-list.component.html',
  styleUrl: './products-list.component.css'
})
export class ProductsListComponent {
  title: string = 'products-app';
  products = products;
  show = false;
  searchKey = ""

  showOrHide = () => {
    this.show = !this.show
  }
}

<div class="card">
  <div class="card-header">{{ title }}</div>
  <div class="card-body">
    <div class="row">
      <div class="col-md-2">Filter by:</div>
      <div class="col-md-4">
        <input type="text" [(ngModel)]="searchKey" />
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <h4>Filtered by:</h4>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>
              <button class="btn btn-primary" (click)="showOrHide()">
                @if(show){Show} @else {Hide} Image
              </button>
            </th>
            <th>Product</th>
            <th>Code</th>
            <th>Available</th>
            <th>Price</th>
            <th>5 Star Rating</th>
          </tr>
        </thead>
        <tbody>
          @for (product of products; track product.productId) {
          <tr>
            <td>
              <img
                *ngIf="show"
                [src]="product.imageUrl"
                [title]="product.productName"
                style="width: 100px"
              />
            </td>
            <td>
              <a>{{ product.productName }}</a>
            </td>
            <td>{{ product.productCode }}</td>
            <td>{{ product.productAvailable }}</td>
            <td>{{ product.price }}</td>
            <td>{{ product.starRating }}</td>
          </tr>
          }
        </tbody>
      </table>
    </div>
  </div>
</div>

// ibm-training/react/products-fetch/src/components/productsList.tsx
import { useCallback, useEffect, useState } from "react"
import HTTPClient from "../api/http"
import IProduct from "../model/product"
import Rating from "./rating"

let portNo = 3000
const title = "Products App"

const ProductsList = () => {
    const [products, setProducts] = useState<IProduct[]>([])
    const [filteredProducts, setFilteredProducts] = useState<IProduct[]>(products)
    const [show, setShow] = useState(false)

    const getProducts = useCallback(async () => {
        const data = (await HTTPClient.get(`http://localhost:${portNo}/products`)) as IProduct[]
        setProducts(data)
        setFilteredProducts(data)
    }, [])

    const searchByName = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        setFilteredProducts(products.filter(p => p.productName.toLocaleLowerCase().includes(e.target.value)))
    }, [])

    useEffect(() => { getProducts() }, [])

    const showOrHide = () => setShow(show => !show)

    return (
        <div className='card'>
            <div className='card-header'>
                {title}
            </div>
            <div className='card-body'>
                <div className='row'>
                    <div className='col-md-2'>Filter by:</div>
                    <div className='col-md-4'>
                        <input type='text' onChange={searchByName} />
                    </div>
                </div>
                <div className='row'>
                    <div className='col-md-6'>
                        <h4>Filtered by: </h4>
                    </div>
                </div>
                <div className='table-responsive'>
                    <table className='table'>
                        <thead>
                            <tr>
                                <th>
                                    <button className='btn btn-primary' onClick={showOrHide}>
                                        {show ? "Hide" : "Show"} Image
                                    </button>
                                </th>
                                <th>Product</th>
                                <th>Code</th>
                                <th>Available</th>
                                <th>Price</th>
                                <th>5 Star Rating</th>
                            </tr>
                        </thead>
                        <tbody>
                            {filteredProducts.map(product =>
                                <tr>
                                    <td>
                                        {show && <img src={product.imageUrl} title={product.productName} className="avatar" style={{ width: 75, margin: 2 }} />}
                                    </td>
                                    <td><a>{product.productName}</a></td>
                                    <td>{product.productCode}</td>
                                    <td>{product.productAvailable}</td>
                                    <td>{product.price}</td>
                                    <td><Rating rating={product.starRating} /></td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    )

}

export default ProductsList
