// ibm-training/angular/products-spa-forms/src/app/products-list/products-list.component.ts
import { Component, OnInit } from '@angular/core';

import IProduct from '../model/product';
import { ProductClientService } from '../product-client.service';

@Component({
  selector: 'app-products-list',
  templateUrl: './products-list.component.html',
  styleUrl: './products-list.component.css'
})
export class ProductsListComponent implements OnInit{

    products:IProduct[] = []
    filteredproducts:IProduct[] = []
    title: string = 'Products App'
    _searchKey: string=''   //indicatinf it is a private member
    showImage: boolean = false
    errorMessage : string =''

//dependency Injection 
//subscribe only then the products will be called or else it wont be called
    constructor(private clientService : ProductClientService) {

    }
    //similar to react we have used useEffect()
  ngOnInit(): void {
    this.clientService.getProducts().subscribe ({
      next : products => {this.products = products
      this.filteredproducts = products
      },
      error : err => this.errorMessage = err


    })
  }


    get searchKey(): string{
      return this._searchKey
    }
    set searchKey(value:string){
      this._searchKey =value
      this.filteredproducts = this.products.filter((product:IProduct)=>
      product.productName.toLocaleLowerCase().includes(value.toLocaleLowerCase()))
    }

    showOrHide =() => {
      this.showImage =!this.showImage
    }
    onRatingClicked(message:string):void{
      this.title=`Product List ${message}`
    }
}
<div class='card'>
    <div class='card-header'>
    {{title}}
    </div>
    <div class='card-body'>
    <div class='row'>
    <div class='col-md-2'>Filter by:</div>
    <div class='col-md-4'>
    <input type='text' [(ngModel)]="searchKey"/>
    </div>
    
    </div>
    <div class='row'>
    <div class='col-md-6'>
    <h4>Filtered by: </h4>
    </div>
    </div>
    <div class='table-responsive'>
    <table class='table'>
    <thead>
    <tr>
    <th>
    <!-- @if(showImage){
    <button class='btn btn-primary' (click)="showOrHide()" >
    Hide Image
    </button>
    }
    @else{
    <button class='btn btn-primary' (click)="showOrHide()" >
        Show Image
        </button>
    } -->
        <button class='btn btn-primary' (click)="showOrHide()" >
            {{showImage? 'Hide': 'Show'}} Image
        </button>
    </th>
    <th>Product</th>
    <th>Code</th>
    <th>Available</th>
    <th>Price</th>
    <th>5 Star Rating</th>
    </tr>
    </thead>
    <tbody>
    
        @for (product of filteredproducts; track product.productId){
    
    <tr>
    <td>
        <!-- @if (showImage){
    <img  [src]="product.imageUrl" [title]="product.productName" style="width:75px;margin:2px"/>
        }  -->
      
        <img *ngIf="showImage" [src]="product.imageUrl" [title]="product.productName" style="width:75px;margin:2px"/>
             
    </td>
    <td><a [routerLink] = "['/products',product.productId]">{{product.productName}}</a></td>
    <td>{{product.productCode}}</td>
    <td>{{product.productAvailable}}</td>
    <td>{{product.price}}</td>
    <td><app-rating [rating]="product.starRating" (ratingClicked)="onRatingClicked($event)"></app-rating></td>
    
    </tr>

    }
    </tbody>
    </table>
    </div>
    
    </div>
    </div>

// ibm-training/react/product-hooks/src/components/productsList.tsx
import { useState } from "react"
import data from "../data/products"
import IProduct from "../model/product"
import Rating from "./rating"

const ProductsList = () => { 
    const [products, setProducts] = useState<IProduct[]>(data)
    const [filteredProducts, setFilteredProducts] = useState<IProduct[]>(products)
    const [show, setShow] = useState(false)

    const title = "Products App"

    const searchByName = (e: React.ChangeEvent<HTMLInputElement>) => {
        setFilteredProducts(products.filter(p => p.productName.toLocaleLowerCase().includes(e.target.value)))
    }

    const showOrHide = () => setShow(show => !show)

    return (
        <div className='card'>
            <div className='card-header'>
                {title}
            </div>
            <div className='card-body'>
                <div className='row'>
                    <div className='col-md-2'>Filter by:</div>
                    <div className='col-md-4'>
                        <input type='text' onChange={searchByName} />
                    </div>
                </div>
                <div className='row'>
                    <div className='col-md-6'>
                        <h4>Filtered by: </h4>
                    </div>
                </div>
                <div className='table-responsive'>
                    <table className='table'>
                        <thead>
                            <tr>
                                <th>
                                    <button className='btn btn-primary' onClick={showOrHide}>
                                        {show ? "Hide" : "Show"} Image
                                    </button>
                                </th>
                                <th>Product</th>
                                <th>Code</th>
                                <th>Available</th>
                                <th>Price</th>
                                <th>5 Star Rating</th>
                            </tr>
                        </thead>
                        <tbody>
                            {filteredProducts.map(product =>
                                <tr>
                                    <td>
                                        {show && <img src={product.imageUrl} title={product.productName} className="avatar" style={{ width: 75, margin: 2 }} />}
                                    </td>
                                    <td><a>{product.productName}</a></td>
                                    <td>{product.productCode}</td>
                                    <td>{product.productAvailable}</td>
                                    <td>{product.price}</td>
                                    <td><Rating rating={product.starRating} /></td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    )

}

export default ProductsList
